# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FamilyTracker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FamilyTracker
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Analytics'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Messaging'
  pod 'Alamofire', '~> 5.2'
  pod 'SDWebImage', '~> 5.0'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'Floaty', '~> 4.2.0'
  pod 'Panels'
  pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'
  pod 'MSPeekCollectionViewDelegateImplementation'
  
end

target 'FamilyTracker WatchKit App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FamilyTracker WatchKit App


end

target 'FamilyTracker WatchKit Extension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 5.2'
  pod 'SDWebImage', '~> 5.0'
  pod 'FirebaseDatabase'
  pod 'Firebase/Messaging'
  # Pods for FamilyTracker WatchKit Extension

end
